### PR TITLE
Proper header name for systemd service sandboxing

### PR DESCRIPTION
**Pull request by Zanthed**
"Systemd service sandboxing" section is not about "Systemd sandboxing".

### CODE REVIEW

**Comment by madaidans-insecurities** [comment]
Thanks; fixed by https://github.com/madaidans-insecurities/madaidans-insecurities.github.io/commit/29fa22faf03d4af90b218fe4e3b2d536a6ced566.

**Comment by brandsimon** [comment]
Is there a reason that contributors are not credited for their work by merging their commits (with their name)?
(Merge-commits can be avoided by rebasing the branch)

**Comment by brandsimon** [comment]
@madaidan @madaidans-insecurities
Is there a reason that contributors are not credited for their work by merging their commits (with their name)?
(Merge-commits can be avoided by rebasing the branch)

**Comment by madaidans-insecurities** [comment]
The commit linked above contains a lot changes, and it's much simpler for me to just include really small fixes like this one in it as well, rather than having to rebase the branch on top of master and then merge it. I will amend the commit to include names, but I didn't originally see it as a big deal since it's only a few words being changed.

**Comment by madaidans-insecurities** [comment]
https://github.com/madaidans-insecurities/madaidans-insecurities.github.io/commit/6b11d03c1617ed0200dcfa22052926ce1010c961

**Pull request closed without merging**
