### PR TITLE
Added An Alternative to Firefox

### PR DESCRIPTION
**Pull request by Nihal247**
I have added Brave as an alternative to Firefox, if you have another cross-platform private & secure browser in mind, you may add that one too.

The section is called 'Alternative to Firefox'

### CODE REVIEW

**Comment by Nihal247** [comment]
Okay @beerisgood, except from hiding in the crowd, Safari/Chrome/Edge can't be a private choice due to their parent company's privacy practices, as they write browsing & search history, IP address, and what not!

**Comment by Nihal247** [comment]
As per what you said, then Tor can't be a private choice too, as when you use Tor, you glow out in the crowd, so Tor can't be a private choice either!

**Comment by Nihal247** [comment]
This leads to tell me that privacy doesn't exists! (at least until Firefox becomes secure)

**Comment by beerisgood** [comment]
> Okay @beerisgood, except from hiding in the crowd, Safari/Chrome/Edge can't be a private choice due to their parent company's privacy practices, as they write browsing & search history, IP address, and what not!

Privacy theatre from „privacy“ communities. In Safari and Edge you can control telemetry and they’re also list every established connections.

all browser get stuff you list as that’s how browser work. Also ask yourself: did you want trust another party (browser) or keep your data on that company your OS is from. 
same also for Website/ Services. If you use Google services, it doesn’t matter if you use Chrome too or not.

**Comment by Nihal247** [comment]
>  Also ask yourself: did you want trust another party (browser)

Yes, I can't fully trust any browser, unless I make my own one.
>  If you use Google services, it doesn’t matter if you use Chrome too or not.

I don't use Google services.

**Comment by beerisgood** [comment]
> Yes, I can't fully trust any browser, unless I make my own one.
> 

Which wouldn’t make any sense. 

> I don't use Google services.

No YouTube? Google Captcha?

**Comment by Nihal247** [comment]
> No YouTube? Google Captcha?

Yep, no YouTube (but I know how to watch YouTube without YouTube!), I don't face much CAPTCHA's until I am on a blacklisted IP

**Comment by Nihal247** [comment]
> > Yes, I can't fully trust any browser, unless I make my own one.

May I just ask what browser you're using?

**Comment by Nihal247** [comment]
May I just ask what browser you're using @beerisgood?

**Comment by beerisgood** [comment]
> May I just ask what browser you're using @beerisgood?

i use Edge on Windows and Safari on iOS & iPadOS

**Comment by sebix** [comment]
> I don't face much CAPTCHA's until I am on a blacklisted IP (happens with Tor)

That doesn't mean you are not using it. Many website include code from Google, Facebook etc., often not easily visible, but you share your data with them. If you don't see much Google Captcha, this just means that Google already knows enough about you to guarantee that you are human.

**Comment by Nihal247** [comment]
> Goal is hiding in the masses instead of using random browsers and/ or using suspicious browsers.

Fingerprint can be much more complicated than you think! You can't fully hide in the crowd. Things like resolution, browser version, timezone, pixel ratio etc. also matter. You can't change these. Do you think you can truly change these? You actually don't know you can't hide at all! Your comments are lacking context. You are just thinking of using the default browser with default settings make you random! Use https://fingerprintjs.com and I bet you cant change your unique ID, until you don't reinstall your browser! I'll also tell you how you can change this. Open Firefox, enable `privacy.resistFingerprinting` and set to delete cookies and site data when you close Firefox, and see your unique ID change. This provides real protection, with no effect on what configurations you use! (as ultimately the Fingerprint is going to change everytime you restart Firefox) I gave you this link because it's a more accurate test, keeping in mind no test is 100% correct!

**Comment by beerisgood** [comment]
> @beerisgood Fingerprinting can be much more complicated than you think! You can't fully hide in the crowd. Things like screen resolution, browser version, timezone, pixel ratio etc. also matter. They vary from user to user. Do you think you can hide from these? You actually don't know you can't hide at all! Your comments are lacking context. You are just thinking of using the default browser with default settings make you random! Use https://fingerprintjs.com and I bet you cant change your unique ID, until you don't reinstall your browser! (remember to delete all data too!) This unique ID can be used to identify you to a great extent.
>

These tests are nonsense and don’t Display real Tracking which is used on server side 


>  I'll also tell you how you can change this. Open Firefox, enable `privacy.resistFingerprinting` and set to delete cookies and site data when you close Firefox, and see your unique ID change. This provides real protection, with no effect on what configurations you use! (as ultimately the Fingerprint is going to change everytime you restart Firefox) I gave you this link because it's a more accurate test, keeping in mind no test is 100% correct!
>

Firefox is worst browser and using this custom setting only makes you unique. You don’t understand how fingerprinting works

**Comment by Nihal247** [comment]
> These tests are nonsense and don’t Display real Tracking which is used on server side

No, these unique fingerprint ID's could be used by websites to identify you. And many sites already do this practice, see on https://fingerprintjs.com. The problem is you can't even change these ID's!

**Comment by beerisgood** [comment]
> No, these unique fingerprint ID's could also be used by websites to identify you. And many sites already do this practice, see on https://fingerprintjs.com. The problem is you can't even change these ID's!

„Could be used“ is privacy theatre. 
Websites don’t use this crap as it’s not needed and way too slow. 
With changing these „IDs“ you only make it worse. 

read https://grapheneos.org/usage#web-browsing & https://madaidans-insecurities.github.io/browser-tracking.html

**Comment by Nihal247** [comment]
> „Could be used“ is privacy theatre.
> Websites don’t use this crap as it’s not needed and way too slow.

Correction: It's not it could be used, but it's actually used by websites like ebay, booking.com, agoda, yahoo, coinbase etc.
> With changing these „IDs“ you only make it worse.
> 
Explanation?

**Comment by Nihal247** [comment]
Apart from the Tor browser, which browser has the best fingerprinting protection? (Maybe Brave?)

**Comment by 735trv** [comment]
> i use Edge on Windows and Safari on iOS & iPadOS

@beerisgood: Oh, but the Egde browser is not privacy-friendly. As with the rest of the system, telemetry can only be reduced but not completely disabled. Also, every URL (including parameters) will be transmitted to Microsoft. Firefox solves this better. There, malicious URLs (Google Safe Browsing) are downloaded from Mozilla every 30 minutes and are compared locally.

I do not know how safari does that.

**Comment by beerisgood** [comment]
> @beerisgood: Oh, but the Egde browser is not privacy-friendly. 
>
Not true. You can read about all used connections on Microsoft docs.

> As with the rest of the system, telemetry can only be reduced but not completely disabled.
>
Also wrong. Read Microsoft docs.

>Also, every URL (including parameters) will be transmitted to Microsoft.
>
Can be disabled but is privacy theatre.


>Firefox solves this better. There, malicious URLs (Google Safe Browsing) are downloaded from Mozilla every 30 minutes and are compared locally.
> 

Firefox is the worst browser in protecting you against malware and phishing.

**Comment by Nihal247** [comment]
> Btw after the Tor browser, which browser has the best fingerprinting protection? (Possibly Brave?)

?

**Comment by Nihal247** [comment]
> > With changing these „IDs“ you only make it worse.
> 
> Explanation?

?

**Comment by beerisgood** [comment]
> > Btw after the Tor browser, which browser has the best fingerprinting protection? (Possibly Brave?)
> 
> ?

Definitely not Brave. It's a joke and fingerprinting their users is very easy.
Fingerprinting also doesn't work you think as i already wrote. Anyway, with OS native browser (and Chrome) you will get best results.


> > > With changing these „IDs“ you only make it worse.
> > 
> > 
> > Explanation?
> 
> ?

read the links i posted and stop spamming with single words.

**Comment by Nihal247** [comment]
> Definitely not Brave. It's a joke and fingerprinting their users is very easy.
> Fingerprinting also doesn't work you think as i already wrote. Anyway, with OS native browser (and Chrome) you will get best results.

Okay, suppose I'm using OS's default browser, what about the screen resolution (depends on screen size), timezone (depends on country), browser version (depends on the version of the browser which people use), pixel ration (vary from screen to screen), don't they differ? Can't we be identified uniquely using these. Even hiding in popular browsers, we can be identified easily. Sites like fingerprintjs.com, assign a unique ID to every visitor and the websites, using fingerprintjs.com uniquely identify us (as it can't be changed!)

My conclusion is that the 3rd party bot protection services are also now so advanced that it is impossible to prevent fingerpinting. My opinion is that this is ultimately a waste of time & resources, because it is a battle that can't be won.

**Comment by beerisgood** [comment]
> Brave provides randomization, which changes our fingerprint periodically. 
>

Doesn't work. In fact, it only ends in uniqueness. Server-side tracking is also used since years. Using client modification only makes it worse for you.
The goal is to hide in the masses, instead of using random browser and/ or using nonsense "tweaks".

>and Tor uses generalization, which makes all the users the same!
> 

Don't work neither as most user modify their browser settings and/ or install extensions. Tor browser only works if settings aren't changed.
Tor user can also be identified with CSS: https://matt.traudt.xyz/posts/how-css-alone-can-help-track-you-YF4ciVY6/

> Nevertheless, suppose I'm using my OS's default browser, what about the screen resolution (depends on screen size of all users), timezone (depends on country), browser version (depends on the version of the browser which people use), pixel ratio (vary from screen to screen), don't they differ? Can't we be identified uniquely using these. Even hiding in popular browsers, we can be identified easily. Sites like fingerprintjs.com, assign a unique ID to every visitor and the websites, using fingerprintjs.com uniquely identify us (as the ID can't be changed!)
> 

Not important. Don't fall to these fingerprint test sites nonsense and privacy theatre generally.

> Your provided links, don't tell how changing these unique ID only makes it worse!
>

https://www.reddit.com/r/GrapheneOS/comments/ciizae/vanadium_and_bromium_privacy/ev6m2ot?utm_source=share&utm_medium=web2x&context=3

**Comment by 735trv** [comment]
> > @beerisgood: Oh, but the Egde browser is not privacy-friendly.
> 
> Not true. You can read about all used connections on Microsoft docs.
> 
> > As with the rest of the system, telemetry can only be reduced but not completely disabled.
> 
> Also wrong. Read Microsoft docs.

@beerisgood Perhaps you are confusing things. You can switch off the optional diagnostic data, but not the required diagnostic data. The button for this is missing. See screenshot:

screenshot


> > Also, every URL (including parameters) will be transmitted to Microsoft.
> 
> Can be disabled but is privacy theatre.
> 
> > Firefox solves this better. There, malicious URLs (Google Safe Browsing) are downloaded from Mozilla every 30 minutes and are compared locally.
> 
> Firefox is the worst browser in protecting you against malware and phishing.

@beerisgood Who said I wanted to disable it? Sure you can, but why? I'm only talking about the technical implementation for matching with malicious domains. Local matching is definitely better than sending the complete URL with parameters to the cloud. I don't know why this should be privacy theatre... 🤦‍♂️

**Comment by Nihal247** [comment]
>Local matching is definitely better than sending the complete URL with parameters to the cloud.

No, @735trv, Firefox sends a unique identifier called 'wrkey' to Google, every time it scans the file you downloaded!

>Webpage and technical data to Google’s SafeBrowsing service: To help protect you from malicious downloads, Firefox sends basic information about unrecognized downloads to Google's SafeBrowsing Service, including the filename and the URL it was downloaded from. Learn more or read Google’s Privacy Policy. Opting out prevents Firefox from warning you of potentially illegitimate or malicious websites or downloaded files.

https://www.mozilla.org/en-US/privacy/firefox/

See this 👉 http://electroholiker.de/?p=1594 for wrkey (it's in German, please translate it).

**Comment by 735trv** [comment]
@Nihal247: First, there is a difference between downloading a file and visiting a website. Second, **any application** that wants to use Google Safe Browsing **needs** an API Key. Brave needs one too, see [here](https://github.com/brave/brave-browser/blob/master/README.md#enabling-third-party-apis). Maybe the `BraveServiceKey` is used for this, because a quick search in the source code shows this: https://github.com/brave/brave-core/blob/master/app/brave_strings.grd#L562-L564

But that's not the point, because both browsers use the same endpoint to download the hashed list of bad domains:
`/v4/threatListUpdates:fetch`

It doesn't matter if you do it with a Brave proxy or fetch it directly from Google, because in both cases the comparison happens locally.

`wrkey` doesn't exist anymore (unless you mean `key`, then sorry but read the docs: https://developers.google.com/safe-browsing/v4/update-api)

**Comment by Nihal247** [comment]
> `wrkey` doesn't exist anymore

Thanks for letting me know, but Brave's SafeBrowsing check is still better than Firefox's! (Don't glorify Firefox's security checks here, it's the worse in the security criteria!).

**Comment by 735trv** [comment]
> but Brave's SafeBrowsing check is still better than Firefox's! 

Why? Where is the difference? Both use the same endpoint and both need API keys to get the lists.

> (Don't glorify Firefox's security checks here, it's the worse in the security criteria!).

I'm only talking about using Google Safe Browsing.

**Comment by Nihal247** [comment]
> Why? Where is the difference? Both use the same endpoint and both need API keys to get the lists.

After using the API keys to get the list and after comparing, Firefox sends certain information like URL, name, file, origin,  size, cryptographic hash etc. to Google.

After using the API keys to get the list and after comparing Brave sends nothing to Google (as Brave-run server doesn't keeps any logs and just compares!).

**Comment by 735trv** [comment]
Brave does the same, but sends everything through a proxy, see https://github.com/brave/brave-browser/issues/6267. A proxy can have advantages but also disadvantages. Whether you see a MitM as an advantage or disadvantage depends on what you want.

Correct, Firefox sends the same information without proxy directly to Google, but only
- on Windows
- for executable files (exe, bat, cmd, msc ...)
- if the executable doesn't have a valid signature

https://wiki.mozilla.org/Security/Features/Application_Reputation_Design_Doc#High-level_overview
https://www.ghacks.net/2014/07/23/prevent-firefox-sending-download-information-google/

If I want to communicate with an interface, then I should communicate directly with this interface and do not route the traffic through other servers. However, everyone can do that as he wants. In my opinion, such an interface is useless (doesn't matter if offered by Google, Microsoft, Mozilla, Apple, AWS, Norton, Kaspersky or anything else).

But that was not my point in [this comment](https://github.com/madaidans-insecurities/madaidans-insecurities.github.io/pull/30#issuecomment-913146487), because both browsers get the list and check locally. Edge (and others) does this very miserably, comparing nothing and sending every address to Google or Microsoft and matching it there. I think that the difference between local and remote is very important and you'll agree.

**Comment by Nihal247** [comment]
I agree, but Firefox sending all the above mentioned information only on Windows shouldn't be taken lightly, as majority of its users are on Windows. However, do we know why Firefox sends this information without a proxy only on Windows?

**Comment by 735trv** [comment]
> why Firefox sends this information (..) only on Windows

I think it's because, as you say, many people use Windows. Especially people who have low or very low experience with computers. Executable files can be run in Windows with a double click. If they are downloaded via the browser, even with just one click. On other OS normally not.

Maybe you can find an answer here: 
https://github.com/brave/brave-browser/issues/4341

> why Firefox sends this information without a proxy

The ToS of Google APIs contain:

> You will only access (or attempt to access) an API by the means described in the documentation of that API. If Google assigns you developer credentials (e.g. client IDs), you must use them with the applicable APIs. **You will not misrepresent or mask either your identity or your API Client's identity when using the APIs** or developer accounts.

Maybe Brave has the permission to use a proxy (or they don't care) and Mozilla didn't get the permission. However, [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1516251) is an issue at Mozilla with a priority of P5, which is very low. Doesn't look like this is needed by many. Maybe because it can be disabled easily.

**Comment by madaidans-insecurities** [comment]
The article is solely a security comparison; it is not the suitable place for recommendations. There is a separate security advice page for that.

**Pull request closed without merging**
