### PR TITLE
Automatically detect dark mode

### PR DESCRIPTION
**Pull request by qua3k**
Uses prefers-color-scheme but allows the button to override it

### CODE REVIEW

**Comment by D3SOX** [comment]
I would add a small check because `window.matchMedia` may be undefined on some browsers

**Comment by qua3k** [comment]
> I would add a small check because `window.matchMedia` may be undefined on some browsers

Could include the `matchMedia` polyfill but browsers that old will not have support for either `prefers-color-scheme` or arrow functions

**Comment by qua3k** [comment]
@madaidan how would you feel about placing the JavaScript in the head to avoid unstyled content

**Comment by qua3k** [comment]
Want to inline it but it would make CSP even less useful

**Comment by Seirdy** [comment]
@qua3k Inlining wouldn't be a big deal if the CSP only allows scripts matching a hash, but IDK if it's possible to set set this up with GitHub Pages.

**Comment by Zanthed** [comment]
> @qua3k Inlining wouldn't be a big deal if the CSP only allows scripts matching a hash, but IDK if it's possible to set set this up with GitHub Pages.
@Seirdy 

It's somewhat possible. You can use the `<meta>` tag with the `http-equiv` attribute in `<head>`, but it's not really considered a good practice compared to the general standard of having it sent as a HTTP header by the server.

**Comment by qua3k** [comment]
> @qua3k Inlining wouldn't be a big deal if the CSP only allows scripts matching a hash, but IDK if it's possible to set set this up with GitHub Pages.

I _could_ do that but madaidan doesn’t want to inline everything

**Pull request closed without merging**
